telegramNewsDigest:
  digestChannelUsernames:
    - "markettwits"
    - "headlines_for_traders"
    - "cbrstocks"
  portfolioTickers:
    - "POSI"
    - "X5"
    - "T-технологии"
    - "BELU"
    - "YANDEX"
    - "Русгидро"
    - "ТГК-14"
    - "ГТЛК"
    - "Полипласт"
    - "ГМК Норникель"
    - "ВИС"
    - "ОФЗ"
  digestSemanticKeywords:
    - "россия"
    - "рф"
    - "цб"
    - "банк россии"
    - "ключевая ставка РФ"
    - "процентная ставка РФ"
    - "инфляция РФ"
    - "денежно-кредитная политика РФ"
    - "монетарная политика РФ"
    - "офз"
    - "минфин РФ"
    - "валютный рынок РФ"

emailReader:
  accountName: "gmail"
  email: "timur.tsedik@gmail.com"
  imapHost: "imap.gmail.com"
  imapPort: 993
  imapSsl: true
  smtpHost: "smtp.gmail.com"
  smtpPort: 465
  smtpSsl: true
